### ISSUE TITLE
Explore Dalli configuration/issues

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1278]
We're seeing issues with Dalli not being found in Loggly. 

https://github.com/mperham/dalli

**Comment by galacto** [comment]
@chcholman any specific errors? will help me : ) thanks

**Comment by zazaian** [comment]
Looks like Dalli just isn't configured properly in the app at all. We need to add the 'connection_pool' gem, and additionally add some config settings through an initializer that also just doesn't seem to be present. I'll take a look at this when I get a moment, or anyone else that's interested in exploring this is welcome to.

**Comment by zazaian** [comment]
Seems to be configured properly in /config/environments/production.rb. @galacto: is it possible that MEMCACHED_URL isn't set here?

config.cache_store = :dalli_store, ENV['MEMCACHED_URL'], { :namespace => 'gradecraft_production', :expires_in => 1.day, :compress => true }

**Comment by galacto** [comment]
Memcached_url variable is set correctly as 
MEMCACHED_URL=gcmemcached-prod:11211

in addition to that there are couple of more env variables set, could you please try and use following ENV variables in production?  I believe instead of using host name host ip will work
following are the variables and their example values 
GCMEMCACHED_PROD_SERVICE_HOST=10.0.25.152
GCMEMCACHED_PROD_PORT_11211_TCP_PORT=11211
GCMEMCACHED_PROD_PORT_11211_TCP=tcp://10.0.25.152:11211

**Comment by galacto** [comment]
Memcached_url variable is set correctly as 
MEMCACHED_URL=gcmemcached-prod:11211

in addition to that there are couple of more env variables set, could you please try and use following ENV variables in production?  I believe instead of using host name host ip will work
following are the variables and their example values 
GCMEMCACHED_PROD_SERVICE_HOST=10.0.25.152
GCMEMCACHED_PROD_PORT_11211_TCP_PORT=11211
GCMEMCACHED_PROD_PORT_11211_TCP=tcp://10.0.25.152:11211

**Comment by chcholman** [comment]
@galacto Awesome! Thank you for finding those. Can you share the same for staging so that we can try this there first?

**Comment by galacto** [comment]
GCMEMCACHED_SERVICE_HOST=10.0.89.143
GCMEMCACHED_PORT_11211_TCP_PORT=11211
GCMEMCACHED_PORT_11211_TCP=tcp://10.0.89.143:11211

mostly remove PROD_

**Comment by chcholman** [comment]
@galacto what's the MEMCACHED_URL set to for staging at the moment?

**Comment by galacto** [comment]
ENV MEMCACHED_URL gcmemcached:11211
