### ISSUE TITLE
Add UM user in interface

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1391]

**Comment by jwright** [comment]
@chcholman Can you expand a bit on this feature request?

**Comment by chcholman** [comment]
@jwright Yup! Should parallel the UM import you built: 

1) Enter email ending with @umich.edu or uniqname 
2) Ask the user creating the account if they want to trigger the welcome email (default yes)
3) Not have to enter a password
4) Automatically activate
5) Set the uniqname portion to be the username, and kerberos_uid

**Comment by jwright** [comment]
@chcholman Thank you but I am still missing something. Am I performing this in an interface somewhere?

**Comment by chcholman** [comment]
@jwright So sorry, yes. 

The goal is to make this possible through the users/new form. Could probably be handled through: 

1) A checkbox that notes if they're a UM user or not
2) Confirming that their email ends in umich.edu (Shouldn't be required to start with @umich.edu - we have a variety of users from the medical school whose emails end with @med.umich.edu)

**Comment by jwright** [comment]
@chcholman Question.

The form for the new user already has a `Username` field:
 
![screen shot 2015-11-24 at 12 11 02 pm](https://cloud.githubusercontent.com/assets/35017/11374575/b36e250e-92a4-11e5-9f2c-56f918f981d8.png)

If a user is internal, one of the requirements is to use the uniquname portion of the email for the username. This leads to some odd flow issues. Here are our options:

1. Let the staff member specify the username for internal users. This is the most obvious I feel and probably the best.
2. Replace what the staff member specifies for the username for internal users. This will be odd as the staff member will expect it to be what they entered.
3. Hide the username when the staff member chooses internal user. This is also odd since the staff member already specified a username and they may not notice the field be missing.
4. Fill in the username when the staff member enters the email address and allow the staff member to override this. We can do this for just internal users but this is odd since internal user is specified afterwards. I like this option for everyone (internal and external).

Please let me know what you think or if there are other options you would like to explore. I like option #4 for everyone.

**Comment by chcholman** [comment]
Hmm. Okay so these two processes are confusing to intuitively integrate into one workflow. Let's see if I can outline what makes that challenging and then we can decide to keep them as one or separate it out. 

When they're UM users, their uniqname (what their username for ALL UM things is officially called) is their username, their kerberos_uid, and the first half of their email (which will always end in @umich). So it would make sense when creating a new UM user to just enter their uniqname, first name, and last name (ultimately it would be even better to integrate with the campus directory, and just enter their uniqname to get the latter elements). So I can imagine moving the "UM User" box up, and switch the order of the username/email fields. If you check that first box it autofills with @umich.edu after the uniqname in the email address field. We do need to support the medical school (@med.umich.edu) so the user does need to be able to override that autocompletion.

*whew* Part II

If they're an external user, their email address is their username, so they only need to enter one.

Recommendations for separating out/keeping together?

**Comment by jwright** [comment]
@chcholman I think the best UI would probably be some sort of "tab" interface so the staff member can choose "UM User" / "Regular User" (obviously better labels) and then the form below would adjust appropriately. What do you think?

**Comment by chcholman** [comment]
@jwright Yup, that makes sense.
