### ISSUE TITLE
Assignment copy feature should include attachment

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1534]
As an instructor, when I copy an assignment it should copy the file attachments and media images over as well

**Comment by jwright** [comment]
@chcholman Does this mean that the assignment files on S3 should be copied or should the assignments share the same file?

**Comment by chcholman** [comment]
@jwright Because we store files directly in relationship to the course they're in, it seems like it makes sense to directly copy them on S3 into the appropriate folder. Open to an alternate solution though!

**Comment by jwright** [comment]
@chcholman No, this is should be how it works, I just wanted to make sure.

**Comment by chcholman** [comment]
:+1:

**Comment by jwright** [comment]
@zazaian Oh, keeper of S3 code....I talked with @chcholman and it may be best to have you jump on this....the initial branch https://github.com/UM-USElab/gradecraft-development/tree/1534-assignment-copy-attachments is out there with a broken test that should be a good spot to pick up on.

I was heading down the path of using Carrierwave so it may not be the correct place to leave off on. Please let me know if you have any questions with `ModelCopier` needs.

**Comment by zazaian** [comment]
@jwright sounds good to me, not a problem. I'll definitely hit you up when it comes to the ModelCopier stuff. My guess is that we're going to want to dig through the AWS API for batch copying on S3, or maybe even do it through `s3fs` so we can manage all of the actual S3 work in one or two interactions rather than hundreds or thousands.

Either way, I'll keep this in sight. Thanks for giving me some background on this earlier today.

**Comment by chcholman** [comment]
Start here: https://github.com/UM-USElab/gradecraft-development/tree/1534-assignment-copy-attachments
