### ISSUE TITLE
Email link to zip file corrupts archive link

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#1606]

**Comment by zazaian** [comment]
@chcholman: so I took a look at this and realized that this actually couldn't have worked in our testing because the exports are server-side encrypted and client-side encrypted. We're getting the correct files on the download, they just haven't been decrypted by our Rails 'client' yet. So we've got a couple of options here:

1) Remove the presigned url links from the emails.
2) Remove the client-side encryption from the exports (we could do this if necessary, but the client-side encryption we're using is considerably more secure than just using server-side).
3) Add our own version of amazon's presigned url utility in which the mailers actually provide some kind of limited token for users to directly download those files without having to log in. We could get asenine about the security here and stack up SHA-3 hashes so that it would be pretty much impossible to guess the url to a given file. This is basically what Amazon is doing with their Presigner library. Clicking the link would take the user to an endpoint that would automatically prompt them to download the file.

**Comment by chcholman** [comment]
Thoughts @jwright @acousticrobot @ksofa2?

Context: When an instructor/GSI requests to download all of the submissions for an assignment, they receive an email when it completes. The direct link in the email currently downloads a zip file is encrypted such that it cannot be extracted (the same zip file downloaded from within the UI works perfectly).

**Comment by zazaian** [comment]
I've been thinking about this a little further and since the use case is that a staff member etc. will have the exact link in their email (and won't have to enter any information that could be mis-typed) we could automatically invalidate the token after X attempts for the given /course_id/submission_id/user_id/hash1/hash2 etc. combination, which would make it pretty much uncrackable. Additionally we could log and track ip addresses that are making requests with any inordinate frequency (20x in a minute?) to eliminate the possibility of brute force attacks. With this much security in place I'd feel comfortable leaving a public-facing endpoint open for the purposes of these presigned no-auth downloads.

**Comment by chcholman** [comment]
@zazaian Okay - I feel like the overhead to add the tracking to the email access and invalidate process is a little too much at the moment. If we skip adding that part, is it still possible to enable them to download directly from the email? Is this option 3 above?

**Comment by zazaian** [comment]
Yup, we don't really need to track ips and/or download attempts, just trying to be mindful of security here for sensitive data. It's pretty unlikely that anyone would be able to guess/crack one of these keys, as A) we'd notice spikes of hits coming in on the server, and B) I'm not sure that even with billions of requests would be possible to actually defeat one of these keys through brute-force within the one-week timeframe during which they'd remain valid. So yeah, option #3 even without the bells and whistles is both viable and secure.

**Comment by chcholman** [comment]
@zazaian Great, let's do that.
