### ISSUE TITLE
Switch to cache storage for session data

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2115]
Currently we store session data in the database. Chad thinks this might be some of what is causing our performance issues. We should drop this table, and switch to storing session data in the cache.

**Comment by jonathoy** [comment]
ActiveRecord session store was pulled out of the Rails 4 core framework a loooooooooong time ago and was done so for good reason - the implementation is not scalable as the number of users begin to grow. This ultimately results in way too many read/write operations being performed.

We should switch to using encrypted cookies on the client-side, since it has been and is the default implementation.
