### ISSUE TITLE
HTML displayed in events timeline

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2311]
<img width="694" alt="screen shot 2016-08-20 at 4 01 05 pm" src="https://cloud.githubusercontent.com/assets/234276/17833606/b33a5c40-66ef-11e6-95f9-63fed450b235.png">

**Comment by mariehooper** [comment]
This might require a larger conversation. We need to decide whether to render the html or escape it... the problem is that when you truncate in the middle of HTML, we risk losing end tags - that is why i wanted to strip it out in this module... but I see that people use links. https://github.com/ianwhite/truncate_html is a solution that might work.
