### ISSUE TITLE
Student dashboard shows lowest level as 'next' if student has earned highest

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2555]
![screen shot 2016-10-11 at 9 05 18 am](https://cloud.githubusercontent.com/assets/234276/19271275/f5a933d8-8f91-11e6-9c45-925ed60b95f9.png)

**Comment by mariehooper** [comment]
@chcholman - I can't replicate this bug in dev. Tried toggling caching on and off thinking that might be a culprit, but no dice. Also - this looks like Ling370 (which I dont see the bug in production as Katniss... and it looks like the problem here is with the current level being incorrect. "Getting close to a letter" is right before the 'D' level... not right below the A.
