### ISSUE TITLE
Import students from Canvas

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#2934]
As an instructor, I would like to be able to import the users currently associated with my Canvas site into my GradeCraft site, with the correct roles

A good pattern for this is importing assignments from the Canvas site

**Comment by jonathoy** [comment]
@chcholman Do you know if this task was meant to be a placeholder for something or do you have additional details?

**Comment by jonathoy** [comment]
@chcholman Per the Canvas docs, it seems like it might be possible for someone to have multiple roles in a course:

```
If a user has multiple enrollments in a context 
(e.g. as a teacher and a student or in multiple course sections), 
each enrollment will be listed separately.
```
Source: https://canvas.instructure.com/doc/api/enrollments.html#method.enrollments_api.index

There also is an enrollment state that includes values such as `active`, `invited`, `inactive`....

I can see us filtering out the enrollments to just include `active`, but it seems like that still leaves the possibility for multiple roles. Thoughts on how this should be handled on our end when creating `course_memberships`?

**Comment by chcholman** [comment]
@jonathoy I'd like for us to import their 'highest' role. So, if they have an TA role, that beats out a student role, and student > observer. 

Rock / paper / scissors like...

**Comment by jonathoy** [comment]
So something like `TeacherEnrollment` > `DesignerEnrollment` > `TaEnrollment` > `StudentEnrollment` > ObserverEnrollment?

There is also the matter of there being a `DesignerEnrollment` as possible value for the role, which is similar to a 'TeacherEnrollment' but with slightly less permissions.

I found this doc while researching the differences: https://lsa.umich.edu/content/dam/iss-assets/iss-documents/Canvas_Roles_Permissions.pdf

Since a designer cannot edit grades but can edit everything else essentially, what does that make them in Gradecraft?

**Comment by chcholman** [comment]
@jonathoy Yup!

We don't currently have a parallel to the `DesignerEnrollment` - let's assign them as TA's, and we'll see if there's a request for this a Designer role as we move forward.
