### ISSUE TITLE
Mobile login firefox on Android can't click on hamburger menu

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#3411]

**Comment by mariehooper** [comment]
@chcholman i am assuming inside the app? and student or instructor side?

**Comment by chcholman** [comment]
Outside of the app!

**Comment by mariehooper** [comment]
Just tested this with an android device and it works - it's just not obvious that a hamburger menu is there because the icons arent loading.

**Comment by mariehooper** [comment]
If this person is still having issues, then it could be javascript disabled on their device. Please refer to these instructions to check: https://support.mozilla.org/en-US/questions/1011318

**Comment by chcholman** [comment]
@mariehooper they were actually working on app.gradecraft.com so the icons were working!

**Comment by mariehooper** [comment]
@chcholman - just checked there too. still works. page load time is about 8-10 sec probably due to the background scene loading. so if this button was clicked prior to that, it wouldn't have fired the js to toggle the menu. Need a bit more information from the user. If js is enabled and button was clicked after page has loaded fully, we need to know what version of firefox, etc.
