### ISSUE TITLE
Fuzzy search for users

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#3438]
Currently the user search requires you to enter all of a user's full first or last name in order to match the response. It would be fantastic for the search to be able to match pieces of names instead.

**Comment by jonathoy** [comment]
Per Camille:

On a side note, I had trouble finding my instructor account because when I search all users and only search by my last name no entries are found. I found the info somewhere else and when I input the first name along with the last name or only the first name it returns the entry.

This doesn't seem to be true for all users
