### ISSUE TITLE
Analytics broken in the App environment

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#3448]
As an instructor using the app environment of GradeCraft, I want to be able to access analytics

**Comment by jwright** [comment]
This was fixed with some maintenance on the app and production environments. It turns out they were both stuck.

The solution was already documented in the wiki but the documentation was not found until a Slack conversation was reviled. The documentation was added to the repo as a new [Maintenance section](https://github.com/UM-USElab/gradecraft-development/blob/6d9ac313c16bd581682ca99a491a50e553b64d22/doc/maintenance.md).
