### ISSUE TITLE
Fix "last_login_at" record on User model

### ISSUE THREAD

**Issue by chcholman** [UM-USElab/gradecraft-development#4202]
Currently, we're not properly updating the `last_login_at` field on the User model. It does appear to be updating on the CourseMembership, but that should be checked for appropriate usage (For instance, I believe if you preview as a student, their last_login_at will update on the CourseMembership model and that shouldn't happen).

**Comment by ebarroso7** [comment]
Other issues have come up regarding `last_login_at` ... Laurie has noticed that students in Talent Gateway have `nil` as this value, although they have submissions and grades. Laurie noticed this when she ran the "Final Grades" export which uses the `last_course_login` method in the user.rb model.

TG users that have encountered this are username - aalmehdi id - 12696, and username - 'elderj'. 

Both of these users have a `last_login_at` of `nil` even though they have both submitted assignments and received grades.

**Comment by ebarroso7** [comment]
currently last_login_at is only being used in the "final grades" exporter - course_grades. Other places in the application use last_activity_at which reports the last activity of the user in the whole application (not just for a course). 
In addition to this, last_login_at is only being updated when a user comes in through an LTI connection.

We would like to change this so that it is updated for all four entry ways - SAML, Google Auth, Gradecraft and LTI. This also needs to be specified when a user switches courses inside the gradecraft app -- 'change' function in courses_controller.rb 

`auto_login` is a function used frequently when the user is logging in. This is a good place to look to update the last_login_at  

Entry points have controllers like saml_controller.rb, etc... inside the controller folder.
