### ISSUE TITLE
Clicking "download all submissions" on an assignment erroneously updates the "updated at" timestamp on submissions with attachments 

### ISSUE THREAD

**Issue by maskib** [UM-USElab/gradecraft-development#4423]
### Expected Behavior
I would not expect clicking the "download all submissions" button to change the "updated at" timestamp on a submission.

### Actual Behavior
On a submission, if there is an attached file, clicking the "download all submissions" button for that assignment will update the "updated at" timestamp to the current date and time. Note that this only happens the first time you click the "download all submissions" button after a new student submission has been submitted. If you click "download all submissions" for a second  (or more) time after a new submission has been added, it will not continue to overwrite the timestamp.

### Steps to reproduce
1. Create a submission with an attached file on an assignment
2. As an instructor, view the submission and take note of the "updated at" timestamp
3. Click "download all submissions" for that assignment. 
4. View that submission again. You'll see the "updated at" timestamp has changed to the moment you clicked the "download all submissions" button.

**Comment by adishy** [comment]
* This seems to be an issue with how submission files are used in the Submissions Export  (`services/creates_submissions_export.rb`).
* The last_updated property is (unnecessarily) modified due to line 24 of `services/creates_submissions_export/create_submission_files.rb`, when "unconfirmed" submission files are being checked. 
* This check (`process_unconfirmed_files` in `submission.rb`) essentially runs through all the submission files in a submission and confirms whether they still exist locally. 
* When this check is performed, a "confirmed" status is set (`check_and_set_confirmed_status` in `submission_file.rb`) for the corresponding submission file object. This updates the `file_missing` and `last_confirmed_at` attributes for the submission file object, but also implicitly updates the `last_updated_at` attribute as well, causing the issue that was observed.
---
There are a few possible ways to fix this problem:
* Potentially add a `last_updated_to_display` attribute to `submission_file` that is used in views and is manually updated when the user updates the submission file. This would mean we will have to modify all places in the codebase where `submission_file.last_updated_at` is used (or updated) to indicate when the user last updated the submission file.
* Disable/remove this check for the submissions export. Could potentially work and not cause problems for newer files, but this check is important to maintain backwards compatibility, and to show any missing files in old courses and such.

**Comment by maskib** [comment]
Sounds like the preferred solution would be to use the last_updated_to_display (or add a db column for last updated at by the student/last edited).
